### ISSUE TITLE
unexpected dup behavior when caching is enabled

### ISSUE THREAD

**Issue by therrick** [shioyama/mobility#490]
We're working on switching from Globalize to Mobility and have encountered a problem with some of our code that uses `dup` to create a new product record based on the attributes (including translations) of an existing product. Note that Product includes `translates :name` in its model definition)...

```
original = Product.create!(name: 'test1')

original.id
=> 1

original.name
=> "test1"

copy = original.dup
copy.name = 'test1 copy'
copy.save!

copy.id
=> 2

copy.name
=> "test1 copy"

original.name
=> "test1 copy" # original unexpectedly shows name value that was updated on the dup record

original.reload

original.name
=> "test1" # after reload of original, it shows the correct name value

copy.name
=> "test1" # but now the copy shows the wrong value
```

Everything behaves correctly if we turn Mobility caching off, either globally or for the individual attribute that we are interacting with (i.e. `translates :name, cache: false`). 

I don't really want to turn off caching universally or for any translated attribute we might need to modify on a dup'd record. I've tried overriding caching on a per read/write basis in the code that interacts with the dup'd copy, but haven't been able to come up with any combination that works.

In case it's significant, here are the defaults we've overridden in the mobility config:
```
backend :table
dirty
fallbacks
locale_accessors
```

We're currently on ruby 2.6.2 and rails 5.1.7.

**Comment by shioyama** [comment]
Thanks for the report! And thanks for identifying the issue in caching. I'll try to have a look in the next week or two.

**Comment by shioyama** [comment]
Oh I think this might be simple. We just need to ensure that the cache is copied over to the new instance when `dup`ing the model. Currently both instances are pointing to the same cache, which is why this happens.

**Comment by shioyama** [comment]
Ok I can't reproduce this. And in fact, Mobility handles duping here, in the backend plugin:

https://github.com/shioyama/mobility/blob/d9bceebf274b04f0dc655b9f82e4e16e4c18034f/lib/mobility/plugins/backend.rb#L128-L131

So it clears the backends hash when duplicating, which should avoid the problem you're seeing. Can you reproduce the problem in a vanilla app, or write a failing test?

**Comment by shioyama** [comment]
Sorry never mind, I can reproduce when I use the "table" backend. So it must be the table-backend-specific cache code that is the problem.

**Comment by shioyama** [comment]
Ok the problem is very clear, and wasn't caught because although there are dup examples, they were only being run against the Table backend _without_ caching enabled :man_facepalming: 

Although the problem is clear I'm not yet sure of a solution. I might just hack something temporary to fix the issue for now so we can release it, then clean it up later :thinking: 

Anyway thanks for noticing! Important issue to fix.

@pwim I think you dup with the table backend (you authored the original fix in https://github.com/shioyama/mobility/pull/84). Have you noticed this issue? It might have cropped up in the meantime.

**Comment by shioyama** [comment]
This has been fixed in [1.0.5](https://rubygems.org/gems/mobility/versions/1.0.5).

**Comment by pwim** [comment]
> @pwim I think you dup with the table backend (you authored the original fix in #84). Have you noticed this issue? It might have cropped up in the meantime.

@shioyama We never ran into this issue because our code was using the dupped object to pre-populate a form, and so we never persisted the dup itself.

**Comment by therrick** [comment]
@shioyama - thanks for the attention on this. Unfortunately, I tried the new release and it still doesn't seem to work as I would expect.

I created a small project to demonstrate the problem: https://github.com/therrick/mobility-demo

The project includes the following spec...
```
RSpec.describe Product, type: :model do
  it "does not change original when updating properties on dup'd object" do
    original = Product.create!(name: 'test1')
    copy = original.dup
    copy.name = 'test1 copy'
    expect(copy.name).to eq 'test1 copy'
    expect(original.name).to eq 'test1'
  end
end
```

The spec passes when mobility cache is disabled, but fails with the following result when cache is enabled...
```
  1) Product does not change original when updating properties on dup'd object
     Failure/Error: expect(original.name).to eq 'test1'

       expected: "test1"
            got: "test1 copy"

       (compared using ==)
     # ./spec/models/product_spec.rb:9:in `block (2 levels) in <top (required)>'
```

**Comment by shioyama** [comment]
Can confirm this is still broken, not sure why... I'll look into it.

**Comment by shioyama** [comment]
Ah figured it out, `options[:cache]` is `nil` so it's not going into the conditional which resets the cache... 

Seems like the fix would be to merge `options` instead of `original_options` here:

https://github.com/shioyama/mobility/blob/7c25fe9d33c0ad2a49a0639bdeefc12c3385f2e0/lib/mobility/plugins/backend.rb#L86

I'll have a look later, thanks for re-flagging the issue.

**Comment by shioyama** [comment]
Ok #502 should finally fix this. I'll also make a PR to the 1-0 branch and release that tomorrow as 1.0.6.

**Comment by therrick** [comment]
Thanks @shioyama. I tested the fix from #502 in both my demo project and in our full app and it solves the problem we were seeing. I really appreciate your help on this.

**Comment by shioyama** [comment]
Thanks for checking! Released [1.0.6](https://rubygems.org/gems/mobility/versions/1.0.6) which should finally fix this.
