### ISSUE TITLE
Does not work with subclassing in production only - dangerous bug

### ISSUE THREAD

**Issue by mrbrdo** [shioyama/mobility#566]
Okay so this bit me because the bug is only present when `config.cache_classes = true` in Rails.
I have a model that is using STI in the normal ActiveRecord way (type column). I add mobility/translates to the base class as normal.

Now the subclasses' translations will work fine in development. But if you turn on cache_classes (as is with production), reading any translated attribute will throw `KeyError: No backend for: myattr` `Caused by KeyError: key not found: :myattr`. The backend classes is an empty Hash on the class.

Would appreciate help or fix on this soon as I had to totally revert my migration from globalize to mobility due to this.

**Comment by mrbrdo** [comment]
The above PR seems to fix it for me, but please check.

**Comment by mrbrdo** [comment]
Nevermind my above PR.

The issue is that it depends when you create the subclass and when you call translates on the base class. It will not work if the subclass is created before translates is called on base class. The proper solution would be to keep a reference to the base classes backends / delegate to it. The added bonus of that is the mobility_backend_classes doesn't need to be frozen I think.

**Comment by mrbrdo** [comment]
I believe I found a solution with #568 
I think an extra issue I had is that my class was a subclass of a subclass of a mobility class. For that reason the mobility_backend_classes were empty. Need to look through all superclasses and not just the immediate superclass.
I have something like this:
```ruby
class A
  extend Mobility
  translates :name 
end

class B < A
end

class C < B
end
```
I guess the existing solution would work for B, but it didn't work for C.

**Comment by shioyama** [comment]
Ok I created an app, set `cache_classes` to `true` in dev mode, created a class and two subclasses, and didn't see any issues. So I can't reproduce this.

I'm going to close this, but if you have a failing test that can reproduce the issue I'm happy to revisit. It could be a corner case I'm missing or compatibility with another gem.

**Comment by mrbrdo** [comment]
I updated the PR with a test for the STI issue. This issue is also fixed by that PR, I don't have time to really make a failing test for this specific one, but the reason it fixes this too is because I only copy mobility_backend_classes from parent upon first access instead of on creating the subclass. This gives a much more flexible window for "plugins" etc. to add translates to existing classes/subclasses.
With current master, if you add a translates to the base class after creating a subclass, the subclass will not include this backend. In practical terms this covers "plugins" adding translations to existing classes. Specifically I had this issue when adding mobility to Spree commerce.

**Comment by shioyama** [comment]
@mrbrdo Very sorry for taking so long to respond to this one, you did a really great and thorough investigation and put together a good fix :bowing_man: 

I've merged and shipped this in 1.2.8!

**Comment by mikhaillopandia** [comment]
[shioyama](https://github.com/shioyama) i'm still facing this issue in STI case in 1.2.9
